# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  helium = {
    pname = "helium";
    version = "0.11.5.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.11.5.1/helium-0.11.5.1-x86_64.AppImage";
      sha256 = "sha256-Ni7IZ9UBafr+ss0BcQaRKqmlmJI4IV1jRAJ8jhcodlg=";
    };
  };
  karere = {
    pname = "karere";
    version = "v3.0.2";
    src = fetchFromGitHub {
      owner = "tobagin";
      repo = "karere";
      rev = "v3.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-V1Cqc9leztK8TRBovPLwnq2AAsTq1l5MUPPA/x2rtls=";
    };
  };
  mango = {
    pname = "mango";
    version = "0.12.9";
    src = fetchFromGitHub {
      owner = "mangowm";
      repo = "mango";
      rev = "0.12.9";
      fetchSubmodules = false;
      sha256 = "sha256-RP7eVqbnQ/uNCXh0HH8SXRIerMlkyHco+wpI9oxon0U=";
    };
  };
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
      fetchSubmodules = false;
      sha256 = "sha256-9gO+GkNoGsxAbMRrBWu0FfXEQtyTmHivlaxlYLpV2YM=";
    };
    date = "2025-12-06";
  };
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
      fetchSubmodules = false;
      sha256 = "sha256-+eVga4b7KIBnfrtmlgq/0HNjQVS3SK6YWVXCPvOeOOc=";
    };
    date = "2025-04-04";
  };
  niri = {
    pname = "niri";
    version = "83e839762fa208b3631163e85d760e0e89fe8fe3";
    src = fetchFromGitHub {
      owner = "niri-wm";
      repo = "niri";
      rev = "83e839762fa208b3631163e85d760e0e89fe8fe3";
      fetchSubmodules = false;
      sha256 = "sha256-PHwfKjDSe1TtW7ndaZbsGbx/nv2ZN+mkst1dquS8vqo=";
    };
    date = "2026-04-26";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "093c1a79f58daab358199c4246de50357e5bf462";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "093c1a79f58daab358199c4246de50357e5bf462";
      fetchSubmodules = false;
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2025-07-26";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "ac82af3e10f9a32cecd9f87ac64b3f9de7c7aea7";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "ac82af3e10f9a32cecd9f87ac64b3f9de7c7aea7";
      fetchSubmodules = false;
      sha256 = "sha256-svc7I2E+tVMEUWUvIS6i3oTGfLq13eaI61T0c1MQ8qQ=";
    };
    date = "2026-04-23";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "aaec6e26e525bd146354a5137ec40f1f23257a4e";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "aaec6e26e525bd146354a5137ec40f1f23257a4e";
      fetchSubmodules = false;
      sha256 = "sha256-/+KiuGUox763dMQvHl1l3+Ci3vL8NwRuKNu9pi3gjyE=";
    };
    date = "2026-01-16";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2026.03.17";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2026.03.17";
      fetchSubmodules = false;
      sha256 = "sha256-A4LUCuKCjpVAOJ8jNoYaC3mRCiKH0/wtcsle0YfZyTA=";
    };
  };
}
