# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  helium = {
    pname = "helium";
    version = "0.17.0.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.17.0.1/helium-0.17.0.1-x86_64.AppImage";
      sha256 = "sha256-JmqdEwoXP/2GGAMS2gjAq7G2oWFuyUTr5ouMDhSOcHY=";
    };
  };
  karere = {
    pname = "karere";
    version = "cef-150.0.10-proprietary-codecs";
    src = fetchFromGitHub {
      owner = "tobagin";
      repo = "karere";
      rev = "cef-150.0.10-proprietary-codecs";
      fetchSubmodules = false;
      sha256 = "sha256-In7sBZF3LxTa0+dY9MM4PlJ2tos7IiTOD33TxlM3YUo=";
    };
  };
  mpv-deletefile = {
    pname = "mpv-deletefile";
    version = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
    src = fetchFromGitHub {
      owner = "zenyd";
      repo = "mpv-scripts";
      rev = "62f4bb313c6cb6366672e78dea940e9da8fec84a";
      fetchSubmodules = false;
      sha256 = "sha256-9gO+GkNoGsxAbMRrBWu0FfXEQtyTmHivlaxlYLpV2YM=";
    };
    date = "2025-12-06";
  };
  mpv-sub-select = {
    pname = "mpv-sub-select";
    version = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
    src = fetchFromGitHub {
      owner = "CogentRedTester";
      repo = "mpv-sub-select";
      rev = "26d24a0fd1d69988eaedda6056a2c87d0a55b6cb";
      fetchSubmodules = false;
      sha256 = "sha256-+eVga4b7KIBnfrtmlgq/0HNjQVS3SK6YWVXCPvOeOOc=";
    };
    date = "2025-04-04";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "512a585fff6da5b2a90e5948059b062516ddb2e7";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "512a585fff6da5b2a90e5948059b062516ddb2e7";
      fetchSubmodules = false;
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2026-05-31";
  };
  sidekick-nvim = {
    pname = "sidekick-nvim";
    version = "3d80a47e6375f6d647c9695d3afea6fa1b3275df";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "sidekick.nvim";
      rev = "3d80a47e6375f6d647c9695d3afea6fa1b3275df";
      fetchSubmodules = false;
      sha256 = "sha256-YV4QMU2I+6PwTVdjsh/1Z+WTeLW9spgpugccmsqpxRY=";
    };
    date = "2026-09-08";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "58c4f4e2f4835cc9bf6751f39e3f7c574fc7f55a";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "58c4f4e2f4835cc9bf6751f39e3f7c574fc7f55a";
      fetchSubmodules = false;
      sha256 = "sha256-kwf9+KXOL5JXGDoEGdtwq+JujP8GVoOwDgz76FBM3xk=";
    };
    date = "2026-09-09";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2026.08.19";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2026.08.19";
      fetchSubmodules = false;
      sha256 = "sha256-BM5ZeGTmHq+1xH6G/zsuCtjLgYgfRA11ya0zIHK5p4g=";
    };
  };
}
