-- vim.o.foldcolumn = 'auto:2'
-- vim.o.foldlevel = 99
-- vim.o.foldlevelstart = 99
-- vim.o.foldenable = false

-- require('k1ng.lazy').add_specs({
--   {
--     'nvim-ufo',
--     event = 'DeferredUIEnter',
--     after = function()
--       local ufo = require('ufo')
--       ufo.setup({
--         provider_selector = function()
--           return { 'lsp', 'indent' }
--         end,
--       })
--     end,
--     keys = {
--       { 'zR', desc = 'open all folds' },
--       { 'zM', desc = 'close all folds' },
--     },
--   },
-- })
